config/routes.rb
Rails.application.routes.draw do
  root 'home#gossip'

  get 'user/show'
  
  get 'home/gossip'
  
  get 'home/show_gossip', to: 'home#show_gossip'

  get 'welcome/:first_name', to: 'welcome#first_name'
  
  get '/team', to: 'static#team'

  get '/contact', to: 'static#contact'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    belongs_to :tag_gossip 
    has_many :tags, through: :taggossips
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
    belongs_to :sender, class_name: "User", 
    belongs_to :recipient, class_name: "User", 
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :taggossips 
    has_many :gossips, through: :taggossips
end

app/models/taggossip.rb
class Taggossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city 
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "Privatemessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "Privatemessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def gossip
      @all_gossips= Gossip.all
    end
  
    def show_gossip
      @gossip = Gossip.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def team
    end
  
    def contact
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def show
      @user = User.find(params[:user_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def first_name
      puts "*" * 50
      puts params[:first_name]
      puts "*" * 50
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/gossip.html.erb
<h3>Derniers ragôts</h3>
<div class="card-deck">
    <div class="col-sm-6">
        <% @all_gossips.each do |gossip| %>
          <div class="card border-info text-white bg-info mb-3">
            <div class="card-header bg-light text-warning">
              <%= link_to 'Auteur:', user_show_path(:user_id => gossip.user.id), style: "text-decoration: none" %>
              <%= gossip.user.first_name %> <%= gossip.user.last_name %>
            </div>
            <div class="card-body">
              Titre du ragôt : 
              <h5 class="card-title"><%= gossip.title %></h5>
              <%= link_to 'Détail', home_show_gossip_path(:id => gossip.id), class: 'btn btn-secondary bg-info' %>
            </div>
          </div>
        <% end %>
    </div>
</div>

app/views/home/show_gossip.html.erb
<h2>PAGE POTIN !</h2>

  <p> Voici le potin n° <%= @gossip.id%><br/>
  Son auteur : <%= @gossip.user.last_name %><br/>
  Le titre : <%= @gossip.title %><br/>
  Créé le : <%= @gossip.created_at.strftime('%d/%m/%Y') %><br/>
  Le contenu du potin : <%= @gossip.content %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-info">
      <a class="navbar-brand" href="#">Gossip</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "Home", home_gossip_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
    </nav>

    <%= yield %>
    
  </body>
</html>

app/views/user/show.html.erb
<h2>Profil utilisateur</h2>

  <p> 
  Son prénom et nom : <%= @user.first_name %> <%= @user.last_name %><br/>
  Son email : <%= @user.email %><br/>
  Son age : <%= @user.age %><br/>
  Sa ville : <%= @user.city.name %><br/>
  Ma vie, mon oeuvre: <%= @user.description %>
  </p>

app/views/welcome/first_name.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">BIENVENUE <%= params[:first_name] %> ! </h1>
    <p class="lead">Ici c'est notre super site de potins, il est chouette, non ?</p>
  </div>
</div>